import { WordInsight } from "./types";

const wordInsights: Record<string, WordInsight> = {
  marché: {
    word: "marché",
    root: "marché",
    partOfSpeech: "Nom",
    roleInSentence: "Complément de lieu dans « au marché »",
    infinitive: "—",
    tense: "—",
    mood: "—",
    conjugation: "Nom commun",
    usage: "Lieu où l'on vend et achète des produits.",
    francePronunciation: "mar-shay",
    quebecPronunciation: "mar-shay",
  },
  quartier: {
    word: "quartier",
    root: "quartier",
    partOfSpeech: "Nom",
    roleInSentence: "Complément du nom ou complément de lieu",
    infinitive: "—",
    tense: "—",
    mood: "—",
    conjugation: "Nom commun",
    usage: "Partie d'une ville.",
    francePronunciation: "kar-tyay",
    quebecPronunciation: "kar-tyay",
  },
  rendent: {
    word: "rendent",
    root: "rendre",
    partOfSpeech: "Verbe",
    roleInSentence: "Verbe principal dans « se rendent au marché »",
    infinitive: "rendre",
    tense: "Présent",
    mood: "Indicatif",
    conjugation: "3e personne du pluriel",
    usage: "Dans « se rendre », cela exprime le fait d'aller vers un lieu.",
    francePronunciation: "ronde",
    quebecPronunciation: "ronde",
  },
  prennent: {
    word: "prennent",
    root: "prendre",
    partOfSpeech: "Verbe",
    roleInSentence: "Verbe principal dans « Certains prennent le temps »",
    infinitive: "prendre",
    tense: "Présent",
    mood: "Indicatif",
    conjugation: "3e personne du pluriel",
    usage: "Exprime l'action de prendre ou de consacrer du temps.",
    francePronunciation: "prenn",
    quebecPronunciation: "prenn",
  },
  discuter: {
    word: "discuter",
    root: "discuter",
    partOfSpeech: "Verbe",
    roleInSentence: "Verbe à l'infinitif après « de »",
    infinitive: "discuter",
    tense: "—",
    mood: "Infinitif",
    conjugation: "Infinitif présent",
    usage: "Parler avec quelqu'un, échanger des idées ou des propos.",
    francePronunciation: "dees-ku-tay",
    quebecPronunciation: "dees-ku-tay",
  },
  culturelles: {
    word: "culturelles",
    root: "culturel",
    partOfSpeech: "Adjectif",
    roleInSentence: "Adjectif qualificatif qui décrit « activités »",
    infinitive: "—",
    tense: "—",
    mood: "—",
    conjugation: "Féminin pluriel",
    usage: "Décrit quelque chose lié à la culture, aux arts ou à la vie intellectuelle.",
    francePronunciation: "kul-tu-rel",
    quebecPronunciation: "kul-tu-rel",
  },
};

export function getWordInsight(word: string): WordInsight | null {
  return wordInsights[word] ?? null;
}